### ISSUE TITLE
can you make the depth plot a stand-alone function?

### ISSUE THREAD

**Issue by comery** [yeeus/GCI#1]
Nice tool! 

If I didn't add "-p" to generate the depth plot at first, I have to run it again, which is much more time-consuming. Could you make it a stand-alone function?

**Comment by yeeus** [comment]
That's a good suggestion, I will make this issue open until I add this funtion to the utilities.

**Comment by yeeus** [comment]
I'm sorry for the delay in replying. Because the "plot" function in GCI.py needs the depth list generated by the "filter" function, you may need to provide the generated depth file (with "-g" option) even if there is a stand-alone function for plotting. However, I have made it (in the directory "utility"), and all you need is to rerun GCI.py and get the depth file.
