### ISSUE TITLE
Curated contigs number can be zero ,even less than 1

### ISSUE THREAD

**Issue by Frankie-zju** [yeeus/GCI#10]
The final GCI-score result shows me that the curated contigs number can be zero, which will make the GCI-score infinity according to the formula. 
![image](https://github.com/yeeus/GCI/assets/153146823/61c58751-4a23-47a9-a528-7c32fa0950f7)

**Comment by yeeus** [comment]
Curated contigs number is computed by removing curated gaps on the contig so in few cases, the quality of the assembly is so poor, for example, that the contig might absolutely be "removed" and get the `Curated contigs number` zero. Other users had reported this issue and I had edited the code to make GCI score zero instead of infinity (which will get an error in python in reality). So this is normal for GCI and you maybe need to check your assembly or alignment files.

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
