### ISSUE TITLE
Why not use illumina reads?

### ISSUE THREAD

**Issue by zhangwenda0518** [yeeus/GCI#2]
Useful tool,
I have a question: why not use the common illumina reads, could you add this function?

thanks！

**Comment by yeeus** [comment]
There are some reasons why not use illumina short reads for detecting issues:
1. In this T2T era, we have turned to third-generation sequencing from NGS for genome assembly. NGS reads have little effects on improving the continuity of genomes and therefore I don't include illumina reads in this tool.
2. Due to the short length, mapping of illumina reads usually has more errors than NGS reads, which can be seen when comparing the impacts of HiFi and ONT on GCI (in the table of README) and that would be discussed in the forthcoming paper.
3. Based on above reasons, detected issues using illumina short reads would be numberless and this is meaningless in a way.
