### ISSUE TITLE
only for one chromosome

### ISSUE THREAD

**Issue by JhinAir** [yeeus/GCI#3]
Hi,
when I extract only one chromosome of bam and fasta files to run, GCI stills outputs all chromosomes. The other chromosomes are null but the desired chromosome also failed.

`python /share/home/zhanglab/user/chenquanyu/scripts/GCI/GCI.py -r C022-CHA-S02_2-01.chrY.fa --nano C022-CHA-S02_2-01.chrY.bam -o C022-CHA-S02_2-01_ont -it png -p -ts 5 --force && touch C022-CHA-S02_2-01_ont.GCI.finish`

![C021-CHA-S01_2-01_ont chrY_RagTag](https://github.com/yeeus/GCI/assets/28035521/55bcd6dc-0e9f-47fb-b8d3-5e3ac4b1f805)

Could you please add a parameter for specifically outputing one chromosome or one region?

Thanks

**Comment by yeeus** [comment]
Because GCI was designed for high-quality genome assembly, so you need to input whole genome alignment which means all chromosomes will be plotted. If not, the other chromosomes would be considered as assembled so poorly that having no highly-confident alignments.
And I added the option `-R` to plot specific regions in the new version **v0.2**, so you can input one bed file to specifically plot some regions.

**Comment by yeeus** [comment]
Some others have also inquired about this issue, so I decide to add one option instead of iterating through all headers.
I now reopen this issue until it would be fixed.

**Comment by yeeus** [comment]
Now GCI adds one option `--chrs` to specify chromosomes (in commit `7afb709`)

**Comment by yeeus** [comment]
I will close this issue due to long time of inactivity.
