### ISSUE TITLE
Uniform window size for visualization

### ISSUE THREAD

**Issue by comery** [yeeus/GCI#4]
hi developers,

I noticed in a case, the overall picture looks different from a zoom-in picture of a specific region. I guess this is because you use an adopted window size for different plots with different scales. Making it uniform will be better to compare each other.

![image](https://github.com/yeeus/GCI/assets/8231694/9e30b988-0f22-4911-a126-50dea98c135e)

**Comment by yeeus** [comment]
yeah that's a good suggestion. I have editted the window size as a constant value (50Kb) in the new version (v0.3). I think that would help.

**Comment by comery** [comment]
Why did you close the issue so quickly?  Be patient!
I used the newest version of GCI, but I got the new error as report as the following:
>The length of plotting region (15706) is less than the window size (50000)

Do you have any ideas?

**Comment by yeeus** [comment]
I'm sorry for that.
Anyways, I think the problem was caused by the plot funcion which would generate plots for every chromosomes and coincidentally, your genome assembly has a chromosome (or contig) less than the window size (50Kb by default).
You can lower the window size or using the latest version of plot_depth.py in the directory `utility` with the option `-R` which would  generate plots only for the sepcific regions.
